import { Country } from '@/types'

export const COUNTRIES: Country[] = [
  { code: 'US', name: 'United States', flag: '/flags/us.svg', language: 'En' },
  { code: 'DE', name: 'Germany', flag: '/flags/de.svg', language: 'De' },
  { code: 'GB', name: 'United Kingdom', flag: '/flags/gb.svg', language: 'En' },
  { code: 'CA', name: 'Canada', flag: '/flags/ca.svg', language: 'En' },
  { code: 'AU', name: 'Australia', flag: '/flags/au.svg', language: 'En' },
  { code: 'FR', name: 'France', flag: '/flags/fr.svg', language: 'Fr' },
  { code: 'ES', name: 'Spain', flag: '/flags/es.svg', language: 'Es' },
  { code: 'IT', name: 'Italy', flag: '/flags/it.svg', language: 'It' },
  { code: 'NL', name: 'Netherlands', flag: '/flags/nl.svg', language: 'Nl' },
  { code: 'SE', name: 'Sweden', flag: '/flags/se.svg', language: 'Sv' },
  { code: 'NO', name: 'Norway', flag: '/flags/no.svg', language: 'No' },
  { code: 'DK', name: 'Denmark', flag: '/flags/dk.svg', language: 'Da' },
  { code: 'FI', name: 'Finland', flag: '/flags/fi.svg', language: 'Fi' },
  { code: 'CH', name: 'Switzerland', flag: '/flags/ch.svg', language: 'De' },
  { code: 'AT', name: 'Austria', flag: '/flags/at.svg', language: 'De' },
  { code: 'BE', name: 'Belgium', flag: '/flags/be.svg', language: 'Nl' },
  { code: 'PT', name: 'Portugal', flag: '/flags/pt.svg', language: 'Pt' },
  { code: 'IE', name: 'Ireland', flag: '/flags/ie.svg', language: 'En' },
  { code: 'NZ', name: 'New Zealand', flag: '/flags/nz.svg', language: 'En' },
  { code: 'JP', name: 'Japan', flag: '/flags/jp.svg', language: 'Ja' },
  { code: 'KR', name: 'South Korea', flag: '/flags/kr.svg', language: 'Ko' },
  { code: 'CN', name: 'China', flag: '/flags/cn.svg', language: 'Zh' },
  { code: 'IN', name: 'India', flag: '/flags/in.svg', language: 'Hi' },
  { code: 'BR', name: 'Brazil', flag: '/flags/br.svg', language: 'Pt' },
  { code: 'MX', name: 'Mexico', flag: '/flags/mx.svg', language: 'Es' },
  { code: 'AR', name: 'Argentina', flag: '/flags/ar.svg', language: 'Es' },
  { code: 'CL', name: 'Chile', flag: '/flags/cl.svg', language: 'Es' },
  { code: 'CO', name: 'Colombia', flag: '/flags/co.svg', language: 'Es' },
  { code: 'PE', name: 'Peru', flag: '/flags/pe.svg', language: 'Es' },
  { code: 'VE', name: 'Venezuela', flag: '/flags/ve.svg', language: 'Es' },
  { code: 'RU', name: 'Russia', flag: '/flags/ru.svg', language: 'Ru' },
  { code: 'PL', name: 'Poland', flag: '/flags/pl.svg', language: 'Pl' },
  { code: 'CZ', name: 'Czech Republic', flag: '/flags/cz.svg', language: 'Cs' },
  { code: 'HU', name: 'Hungary', flag: '/flags/hu.svg', language: 'Hu' },
  { code: 'RO', name: 'Romania', flag: '/flags/ro.svg', language: 'Ro' },
  { code: 'BG', name: 'Bulgaria', flag: '/flags/bg.svg', language: 'Bg' },
  { code: 'HR', name: 'Croatia', flag: '/flags/hr.svg', language: 'Hr' },
  { code: 'SI', name: 'Slovenia', flag: '/flags/si.svg', language: 'Sl' },
  { code: 'SK', name: 'Slovakia', flag: '/flags/sk.svg', language: 'Sk' },
  { code: 'LT', name: 'Lithuania', flag: '/flags/lt.svg', language: 'Lt' },
  { code: 'LV', name: 'Latvia', flag: '/flags/lv.svg', language: 'Lv' },
  { code: 'EE', name: 'Estonia', flag: '/flags/ee.svg', language: 'Et' },
  { code: 'GR', name: 'Greece', flag: '/flags/gr.svg', language: 'El' },
  { code: 'TR', name: 'Turkey', flag: '/flags/tr.svg', language: 'Tr' },
  { code: 'IL', name: 'Israel', flag: '/flags/il.svg', language: 'He' },
  { code: 'AE', name: 'UAE', flag: '/flags/ae.svg', language: 'Ar' },
  { code: 'SA', name: 'Saudi Arabia', flag: '/flags/sa.svg', language: 'Ar' },
  { code: 'EG', name: 'Egypt', flag: '/flags/eg.svg', language: 'Ar' },
  { code: 'ZA', name: 'South Africa', flag: '/flags/za.svg', language: 'En' },
  { code: 'NG', name: 'Nigeria', flag: '/flags/ng.svg', language: 'En' },
  { code: 'KE', name: 'Kenya', flag: '/flags/ke.svg', language: 'En' },
  { code: 'TH', name: 'Thailand', flag: '/flags/th.svg', language: 'Th' },
  { code: 'VN', name: 'Vietnam', flag: '/flags/vn.svg', language: 'Vi' },
  { code: 'MY', name: 'Malaysia', flag: '/flags/my.svg', language: 'Ms' },
  { code: 'SG', name: 'Singapore', flag: '/flags/sg.svg', language: 'En' },
  { code: 'PH', name: 'Philippines', flag: '/flags/ph.svg', language: 'En' },
  { code: 'ID', name: 'Indonesia', flag: '/flags/id.svg', language: 'Id' },
]

export const FILTER_OPTIONS = [
  'Rooftop',
  'Live Music',
  'Premium Tobacco',
  'Outdoor Seating',
  'VIP Service',
  'Hookah Bar',
  'Restaurant',
  'Nightclub',
  'Lounge',
  'Cafe',
  'Beachfront',
  'Mountain View',
  'City View',
  'Garden',
  'Terrace',
  'Private Rooms',
  'Shisha Catering',
  'Events',
  'Workshops',
  'Tastings'
]

export const BREAKPOINTS = {
  mobile: '320px',
  tablet: '768px',
  desktop: '1024px',
  wide: '1440px'
} as const

export const Z_INDEX = {
  dropdown: 1000,
  sticky: 1001,
  modal: 1002,
  popup: 1003,
  tooltip: 1004
} as const 